/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UniversalTuringMachine;

import java.io.File;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class App {

    public static void main(String[] args) {

        HashSet<Transition> transitionsMultiplication = TransitionImporter.importSet(new File("./app/src/main/resources/multiplication.csv"));;
        HashSet<Transition> transitionsAddition = TransitionImporter.importSet(new File("./app/src/main/resources/addition.csv"));

        UniversalTuringMachine tm = new UniversalTuringMachine(2, 3, transitionsAddition, false);

        try {
            boolean isRunning = true;
            while (isRunning) {
                isRunning = tm.run();
            }
        } catch (IllegalArgumentException e) {
            System.err.println("Looks like something went wrong...\nError: " + e.getMessage());
        }

        System.out.println("Result of calculation: " + tm.getResult());

    }
}
